use_frameworks!

platform :ios, '10.0'

target 'MFUIAthentication_Example' do
  pod 'MFUIAthentication', :path => '../'

  target 'MFUIAthentication_Tests' do
    inherit! :search_paths

    
  end
end
